services:
    OHMedia\TimezoneBundle\Service\Timezone:
        arguments: ["@security.token_storage", "%oh_media_timezone.timezone%"]

    oh_media_timezone.timezone:
        alias: OHMedia\TimezoneBundle\Service\Timezone

    OHMedia\TimezoneBundle\EventListener\TimezoneListener:
        arguments: ["@oh_media_timezone.timezone"]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }

    OHMedia\TimezoneBundle\Form\Type\DateTimeType:
        arguments: ["@oh_media_timezone.timezone"]
        tags:
            - { name: form.type }
