services:
    _defaults:
        autowire: true
        autoconfigure: true

    OHMedia\TimezoneBundle\:
        resource: '../src/'
        exclude:
            - '../src/Entity/'
            - '../src/OHMediaTimezoneBundle.php'

    OHMedia\TimezoneBundle\EventListener\TimezoneListener:
        autowire: true
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
